[project]
name = "kuzkabuh"
version = "0.1.0"
description = "KUZ’KA.BUH — бухгалтерия для селлеров маркетплейсов"
readme = "README.md"
requires-python = ">=3.11"

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
